# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from raassdkpy.models.language import Language  # noqa: E501

class TestLanguage(unittest.TestCase):
    """Language unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLanguage(self):
        """Test Language"""
        # inst = Language()

if __name__ == '__main__':
    unittest.main()
