# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from raassdkpy.models.user import User  # noqa: E501

class TestUser(unittest.TestCase):
    """User unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> User:
        """Test User
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `User`
        """
        model = User()  # noqa: E501
        if include_optional:
            return User(
                id = '',
                email = '',
                first_name = '',
                last_name = '',
                middle_name = '',
                second_last_name = '',
                address1 = '',
                address2 = '',
                place_id = '',
                country = '',
                address_description = '',
                gender = '',
                dob = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                country_id = '',
                status = 'new',
                phone_number = '',
                phone_verified = True,
                cip = raassdkpy.models.cip.CIP(
                    sent = True, 
                    touched = True, 
                    rejected = True, 
                    manual_required = True, 
                    message = '', 
                    documents = [
                        raassdkpy.models.cip_document.CIPDocument(
                            type = '', 
                            sides = 1.337, 
                            has_mrz = True, 
                            data = raassdkpy.models.cip_data.CIPData(
                                address = '', 
                                city = '', 
                                country = '', 
                                county = '', 
                                district = '', 
                                dob = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                dob_raw = '', 
                                doc_type = '', 
                                exp_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                exp_date_raw = '', 
                                first_name = '', 
                                gender = '', 
                                id = '', 
                                id_country = '', 
                                id_name = '', 
                                last_name = '', 
                                names = '', 
                                nationality = '', 
                                second_lastname = '', 
                                second_name = '', 
                                state = '', 
                                subtype = '', ), 
                            created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                        ], 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    facematch_sent = True, 
                    facematch_ok = True, 
                    facematch_msg = '', ),
                first_time = True,
                country_code = '',
                city = '',
                zipcode = '',
                state = '',
                birth_state = '',
                place_detail = '',
                pincode = '',
                has_pincode = True,
                password = '',
                phone_info = raassdkpy.models.i_phone_info.IPhoneInfo(
                    is_valid = True, 
                    caller_name = '', 
                    country_code = '', 
                    phone_number = '', 
                    carrier = raassdkpy.models.i_phone_info_carrier.IPhoneInfo_carrier(
                        type = '', 
                        name = '', ), ),
                tenant_id = '',
                tenant_code = '',
                latitude = 1.337,
                longitude = 1.337,
                profile_picture_url = '',
                custom_country_code = '',
                facebook_public_user_name = '',
                instagram_public_user_name = '',
                account_code = ''
            )
        else:
            return User(
                id = '',
                tenant_id = '',
                tenant_code = '',
        )
        """

    def testUser(self):
        """Test User"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
