# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from raassdkpyv2.api.partner_api import PartnerApi  # noqa: E501


class TestPartnerApi(unittest.TestCase):
    """PartnerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PartnerApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_add_card(self) -> None:
        """Test case for add_card

        """
        pass

    def test_create_contact(self) -> None:
        """Test case for create_contact

        """
        pass

    def test_delete_payment_method(self) -> None:
        """Test case for delete_payment_method

        """
        pass

    def test_get_cip_info(self) -> None:
        """Test case for get_cip_info

        """
        pass

    def test_get_destination_sof_for_requet_money_operation(self) -> None:
        """Test case for get_destination_sof_for_requet_money_operation

        """
        pass

    def test_get_operation(self) -> None:
        """Test case for get_operation

        """
        pass

    def test_get_operation_status(self) -> None:
        """Test case for get_operation_status

        """
        pass

    def test_get_payment_method(self) -> None:
        """Test case for get_payment_method

        """
        pass

    def test_get_payment_method_v2(self) -> None:
        """Test case for get_payment_method_v2

        """
        pass

    def test_get_user_token(self) -> None:
        """Test case for get_user_token

        """
        pass

    def test_list_contacts(self) -> None:
        """Test case for list_contacts

        """
        pass

    def test_register_user_v2(self) -> None:
        """Test case for register_user_v2

        """
        pass

    def test_request_v2(self) -> None:
        """Test case for request_v2

        """
        pass

    def test_updated_contact(self) -> None:
        """Test case for updated_contact

        """
        pass


if __name__ == '__main__':
    unittest.main()
