# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from raassdkpyv2.models.session_link_params import SessionLinkParams  # noqa: E501

class TestSessionLinkParams(unittest.TestCase):
    """SessionLinkParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SessionLinkParams:
        """Test SessionLinkParams
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SessionLinkParams`
        """
        model = SessionLinkParams()  # noqa: E501
        if include_optional:
            return SessionLinkParams(
                phone_number = '',
                last_name = '',
                last_name2 = '',
                gender = 'Male',
                dob = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                email = '',
                first_name = '',
                middle_name = '',
                address1 = '',
                address2 = '',
                country_code = 'AF',
                city = '',
                zip_code = '',
                state = '',
                birth_state = '',
                add_card_params = raassdkpyv2.models.add_card_session_params.AddCardSessionParams(
                    name = '', 
                    cardtype = 'DebitCard', 
                    number = '', 
                    name_on_card = '', 
                    expiration_date = '', 
                    security_code = '', 
                    currency = '', 
                    country = '', 
                    card_network = 'NotApplicable', )
            )
        else:
            return SessionLinkParams(
                phone_number = '',
                last_name = '',
                first_name = '',
                address1 = '',
                country_code = 'AF',
                city = '',
                state = '',
        )
        """

    def testSessionLinkParams(self):
        """Test SessionLinkParams"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
