# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from raassdkpy.models.country_alpha2_code import CountryAlpha2Code  # noqa: E501

class TestCountryAlpha2Code(unittest.TestCase):
    """CountryAlpha2Code unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCountryAlpha2Code(self):
        """Test CountryAlpha2Code"""
        # inst = CountryAlpha2Code()

if __name__ == '__main__':
    unittest.main()
