# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from raassdkpy.models.cash_operators import CashOperators  # noqa: E501

class TestCashOperators(unittest.TestCase):
    """CashOperators unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CashOperators:
        """Test CashOperators
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CashOperators`
        """
        model = CashOperators()  # noqa: E501
        if include_optional:
            return CashOperators(
                id = '',
                external_id = '',
                network = [
                    raassdkpy.models.cash_network.CashNetwork(
                        id = '', 
                        name = '', 
                        cash_provider = raassdkpy.models.cash_provider.cashProvider(), 
                        image_url = '', )
                    ],
                country = '',
                name = '',
                image_url = '',
                location = [
                    raassdkpy.models.cash_location.CashLocation(
                        id = '', 
                        enable = '', 
                        cash_operator_id = '', 
                        name = '', 
                        address_line1 = '', 
                        address_line2 = '', 
                        state = '', 
                        city = '', 
                        longitude = '', 
                        latitude = '', 
                        phone = '', 
                        image = '', )
                    ],
                cash_account_type = None,
                image_circle_url = ''
            )
        else:
            return CashOperators(
                id = '',
                external_id = '',
                network = [
                    raassdkpy.models.cash_network.CashNetwork(
                        id = '', 
                        name = '', 
                        cash_provider = raassdkpy.models.cash_provider.cashProvider(), 
                        image_url = '', )
                    ],
                country = '',
                name = '',
                image_url = '',
                location = [
                    raassdkpy.models.cash_location.CashLocation(
                        id = '', 
                        enable = '', 
                        cash_operator_id = '', 
                        name = '', 
                        address_line1 = '', 
                        address_line2 = '', 
                        state = '', 
                        city = '', 
                        longitude = '', 
                        latitude = '', 
                        phone = '', 
                        image = '', )
                    ],
                cash_account_type = None,
                image_circle_url = '',
        )
        """

    def testCashOperators(self):
        """Test CashOperators"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
