# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from raassdkpyv2.models.user_token_response import UserTokenResponse  # noqa: E501

class TestUserTokenResponse(unittest.TestCase):
    """UserTokenResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserTokenResponse:
        """Test UserTokenResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserTokenResponse`
        """
        model = UserTokenResponse()  # noqa: E501
        if include_optional:
            return UserTokenResponse(
                user_id = '',
                status = '',
                status_detail = ''
            )
        else:
            return UserTokenResponse(
                user_id = '',
        )
        """

    def testUserTokenResponse(self):
        """Test UserTokenResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
