# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from raassdkpyv2.models.pick_cip_exclude_keyof_cipid_or_attemps_or_is_valid_ofac import PickCIPExcludeKeyofCIPIdOrAttempsOrIsValidOFAC  # noqa: E501

class TestPickCIPExcludeKeyofCIPIdOrAttempsOrIsValidOFAC(unittest.TestCase):
    """PickCIPExcludeKeyofCIPIdOrAttempsOrIsValidOFAC unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PickCIPExcludeKeyofCIPIdOrAttempsOrIsValidOFAC:
        """Test PickCIPExcludeKeyofCIPIdOrAttempsOrIsValidOFAC
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PickCIPExcludeKeyofCIPIdOrAttempsOrIsValidOFAC`
        """
        model = PickCIPExcludeKeyofCIPIdOrAttempsOrIsValidOFAC()  # noqa: E501
        if include_optional:
            return PickCIPExcludeKeyofCIPIdOrAttempsOrIsValidOFAC(
                cip_level = 1.337,
                has_personal_info = True,
                has_proof_of_l_ife = True,
                has_scan_ids = True,
                is_perform_level1 = True,
                is_perform_level2 = True,
                profile_and_ocr_similarity = 1.337,
                errors_process = raassdkpyv2.models.errors_cip_process.ErrorsCIPProcess(
                    error_id_scan_date_expired = '', 
                    error_ofac_not_valid = '', 
                    error_face_match_not_valid = '', 
                    error_photo_scan_id_required = '', 
                    error_ocr_profile_match_not_valid = '', ),
                level1status = 'Pending',
                level1status_detail = 'None',
                level2status = 'Pending',
                level2status_detail = 'None',
                is_document_id_value_validated = True,
                is_alternate_flow = True,
                lola_cip = raassdkpyv2.models.pick_cip_exclude_keyof_cip_id_or_attemps_or_is_valid_ofac___lola_cip.Pick_CIP_Exclude_keyofCIP_id_or_attemps_or_isValidOFAC___lolaCIP(
                    update_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    in_progress = True, )
            )
        else:
            return PickCIPExcludeKeyofCIPIdOrAttempsOrIsValidOFAC(
                cip_level = 1.337,
                has_personal_info = True,
                has_proof_of_l_ife = True,
                has_scan_ids = True,
                is_perform_level1 = True,
                is_perform_level2 = True,
                errors_process = raassdkpyv2.models.errors_cip_process.ErrorsCIPProcess(
                    error_id_scan_date_expired = '', 
                    error_ofac_not_valid = '', 
                    error_face_match_not_valid = '', 
                    error_photo_scan_id_required = '', 
                    error_ocr_profile_match_not_valid = '', ),
                level1status = 'Pending',
                level1status_detail = 'None',
                level2status = 'Pending',
                level2status_detail = 'None',
        )
        """

    def testPickCIPExcludeKeyofCIPIdOrAttempsOrIsValidOFAC(self):
        """Test PickCIPExcludeKeyofCIPIdOrAttempsOrIsValidOFAC"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
