# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from raassdkpy.models.errors_cip_process import ErrorsCIPProcess  # noqa: E501

class TestErrorsCIPProcess(unittest.TestCase):
    """ErrorsCIPProcess unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ErrorsCIPProcess:
        """Test ErrorsCIPProcess
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ErrorsCIPProcess`
        """
        model = ErrorsCIPProcess()  # noqa: E501
        if include_optional:
            return ErrorsCIPProcess(
                error_id_scan_date_expired = '',
                error_ofac_not_valid = '',
                error_face_match_not_valid = '',
                error_photo_scan_id_required = '',
                error_ocr_profile_match_not_valid = ''
            )
        else:
            return ErrorsCIPProcess(
        )
        """

    def testErrorsCIPProcess(self):
        """Test ErrorsCIPProcess"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
