# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from raassdkpy.models.raa_s_partner_payment_method import RaaSPartnerPaymentMethod  # noqa: E501

class TestRaaSPartnerPaymentMethod(unittest.TestCase):
    """RaaSPartnerPaymentMethod unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RaaSPartnerPaymentMethod:
        """Test RaaSPartnerPaymentMethod
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RaaSPartnerPaymentMethod`
        """
        model = RaaSPartnerPaymentMethod()  # noqa: E501
        if include_optional:
            return RaaSPartnerPaymentMethod(
                currency = '',
                bank_account_type = 'CheckingAccount',
                cardtype = 'DebitCard',
                number = '',
                account_number = '',
                bank_entity_number = '',
                bank_name = '',
                is_primary = True,
                name = '',
                id = ''
            )
        else:
            return RaaSPartnerPaymentMethod(
        )
        """

    def testRaaSPartnerPaymentMethod(self):
        """Test RaaSPartnerPaymentMethod"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
