# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from raassdkpy.api.file_api import FileApi  # noqa: E501


class TestFileApi(unittest.TestCase):
    """FileApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FileApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_upload_documents(self) -> None:
        """Test case for upload_documents

        """
        pass

    def test_upload_proof_of_life(self) -> None:
        """Test case for upload_proof_of_life

        """
        pass


if __name__ == '__main__':
    unittest.main()
