# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from raassdkpyv2.models.add_card_partner_params import AddCardPartnerParams  # noqa: E501

class TestAddCardPartnerParams(unittest.TestCase):
    """AddCardPartnerParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AddCardPartnerParams:
        """Test AddCardPartnerParams
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AddCardPartnerParams`
        """
        model = AddCardPartnerParams()  # noqa: E501
        if include_optional:
            return AddCardPartnerParams(
                name = '',
                cardtype = 'DebitCard',
                number = '0',
                is_primary = True,
                name_on_card = '',
                expiration_date = '0',
                security_code = '0',
                currency = '',
                country = '0',
                operation_id = '',
                card_network = 'NotApplicable'
            )
        else:
            return AddCardPartnerParams(
                name = '',
                cardtype = 'DebitCard',
                number = '0',
                is_primary = True,
                name_on_card = '',
                expiration_date = '0',
                country = '0',
                card_network = 'NotApplicable',
        )
        """

    def testAddCardPartnerParams(self):
        """Test AddCardPartnerParams"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
