# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from raassdkpyv2.models.quick_amount import QuickAmount  # noqa: E501

class TestQuickAmount(unittest.TestCase):
    """QuickAmount unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> QuickAmount:
        """Test QuickAmount
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `QuickAmount`
        """
        model = QuickAmount()  # noqa: E501
        if include_optional:
            return QuickAmount(
                amount = 1.337,
                is_most_frequent = True,
                exchange = 1.337,
                currency_code_src = '',
                currency_code_dest = ''
            )
        else:
            return QuickAmount(
                amount = 1.337,
                exchange = 1.337,
                currency_code_src = '',
                currency_code_dest = '',
        )
        """

    def testQuickAmount(self):
        """Test QuickAmount"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
