# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from raassdkpy.models.user_document import UserDocument  # noqa: E501

class TestUserDocument(unittest.TestCase):
    """UserDocument unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserDocument:
        """Test UserDocument
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserDocument`
        """
        model = UserDocument()  # noqa: E501
        if include_optional:
            return UserDocument(
                id = '',
                type = None,
                sub_type = 1.337,
                number = '',
                expiration_date = '',
                issued_country = '',
                issued_date = '',
                user_identity_data = {
                    'key' : null
                    },
                date_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return UserDocument(
                id = '',
                type = None,
                sub_type = 1.337,
                number = '',
        )
        """

    def testUserDocument(self):
        """Test UserDocument"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
