# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from raassdkpyv2.models.level_status_detail import LevelStatusDetail  # noqa: E501

class TestLevelStatusDetail(unittest.TestCase):
    """LevelStatusDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLevelStatusDetail(self):
        """Test LevelStatusDetail"""
        # inst = LevelStatusDetail()

if __name__ == '__main__':
    unittest.main()
