# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from raassdkpyv2.models.operation_user_detail import OperationUserDetail  # noqa: E501

class TestOperationUserDetail(unittest.TestCase):
    """OperationUserDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OperationUserDetail:
        """Test OperationUserDetail
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OperationUserDetail`
        """
        model = OperationUserDetail()  # noqa: E501
        if include_optional:
            return OperationUserDetail(
                profile_picture_url = '',
                country = '',
                image_url = '',
                email = '',
                phone_number = '',
                last_name = '',
                first_name = ''
            )
        else:
            return OperationUserDetail(
                phone_number = '',
        )
        """

    def testOperationUserDetail(self):
        """Test OperationUserDetail"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
