# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from raassdkpy.api.partner_full_api import PartnerFullApi  # noqa: E501


class TestPartnerFullApi(unittest.TestCase):
    """PartnerFullApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PartnerFullApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_create_pin(self) -> None:
        """Test case for create_pin

        """
        pass

    def test_get_available_operation_type(self) -> None:
        """Test case for get_available_operation_type

        """
        pass

    def test_get_available_payment_methods(self) -> None:
        """Test case for get_available_payment_methods

        """
        pass

    def test_get_cip_info(self) -> None:
        """Test case for get_cip_info

        """
        pass

    def test_get_corridors(self) -> None:
        """Test case for get_corridors

        """
        pass

    def test_get_exchange_rates(self) -> None:
        """Test case for get_exchange_rates

        """
        pass

    def test_get_in_and_out_operations(self) -> None:
        """Test case for get_in_and_out_operations

        """
        pass

    def test_get_operation_quote(self) -> None:
        """Test case for get_operation_quote

        """
        pass

    def test_get_profile(self) -> None:
        """Test case for get_profile

        """
        pass

    def test_perform_level_one(self) -> None:
        """Test case for perform_level_one

        """
        pass

    def test_perform_resubmit_upgrade_level(self) -> None:
        """Test case for perform_resubmit_upgrade_level

        """
        pass

    def test_pre_quote(self) -> None:
        """Test case for pre_quote

        """
        pass

    def test_receive(self) -> None:
        """Test case for receive

        """
        pass

    def test_replace_payment_method(self) -> None:
        """Test case for replace_payment_method

        """
        pass

    def test_request_otp(self) -> None:
        """Test case for request_otp

        """
        pass

    def test_send(self) -> None:
        """Test case for send

        """
        pass

    def test_set_alternate_cip(self) -> None:
        """Test case for set_alternate_cip

        """
        pass

    def test_set_level_two(self) -> None:
        """Test case for set_level_two

        """
        pass

    def test_set_trusted_level_two(self) -> None:
        """Test case for set_trusted_level_two

        """
        pass

    def test_update_profile(self) -> None:
        """Test case for update_profile

        """
        pass

    def test_upload_documents(self) -> None:
        """Test case for upload_documents

        """
        pass

    def test_upload_proof_of_life(self) -> None:
        """Test case for upload_proof_of_life

        """
        pass

    def test_validate_otp(self) -> None:
        """Test case for validate_otp

        """
        pass

    def test_validate_pin_code(self) -> None:
        """Test case for validate_pin_code

        """
        pass


if __name__ == '__main__':
    unittest.main()
