# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from raassdkpyv2.models.quote_transaction_base import QuoteTransactionBase  # noqa: E501

class TestQuoteTransactionBase(unittest.TestCase):
    """QuoteTransactionBase unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> QuoteTransactionBase:
        """Test QuoteTransactionBase
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `QuoteTransactionBase`
        """
        model = QuoteTransactionBase()  # noqa: E501
        if include_optional:
            return QuoteTransactionBase(
                sender_user_id = '',
                sender_country_code = '',
                recipient_user_id = '',
                recipient_country_code = '',
                recipient_currency = '',
                recipient_amount = 1.337,
                is_sender_amount = True,
                amount_currency = '',
                amount = 1.337,
                operation_type = None,
                source_payment_method = None,
                destination_payment_method = None,
                tennant_fee = 1.337
            )
        else:
            return QuoteTransactionBase(
                sender_country_code = '',
                recipient_user_id = '',
                recipient_country_code = '',
                recipient_currency = '',
                recipient_amount = 1.337,
                is_sender_amount = True,
                amount_currency = '',
                amount = 1.337,
                operation_type = None,
                source_payment_method = None,
        )
        """

    def testQuoteTransactionBase(self):
        """Test QuoteTransactionBase"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
