# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from raassdkpyv2.models.raas_quote_transaction_response import RaasQuoteTransactionResponse  # noqa: E501

class TestRaasQuoteTransactionResponse(unittest.TestCase):
    """RaasQuoteTransactionResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RaasQuoteTransactionResponse:
        """Test RaasQuoteTransactionResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RaasQuoteTransactionResponse`
        """
        model = RaasQuoteTransactionResponse()  # noqa: E501
        if include_optional:
            return RaasQuoteTransactionResponse(
                id = '',
                source_currency = '',
                destination_currency = '',
                reason = '',
                reason_detail = None,
                source_amount = 1.337,
                amount = 1.337,
                destination_amount = 1.337,
                exchange_rate = 1.337,
                tax = 1.337,
                source_fee = 1.337,
                destination_fee = 1.337,
                transaction_fee = 1.337,
                sender_charge_back = 1.337,
                recipient_charge_back = 1.337,
                is_executable = True,
                valid_time_in_minutes = 1.337,
                tenant_fee = 1.337,
                sender_user_id = ''
            )
        else:
            return RaasQuoteTransactionResponse(
                source_currency = '',
                destination_currency = '',
                reason = '',
                reason_detail = None,
                source_amount = 1.337,
                amount = 1.337,
                destination_amount = 1.337,
                exchange_rate = 1.337,
                tax = 1.337,
                source_fee = 1.337,
                destination_fee = 1.337,
                transaction_fee = 1.337,
                sender_charge_back = 1.337,
                recipient_charge_back = 1.337,
                is_executable = True,
                valid_time_in_minutes = 1.337,
                tenant_fee = 1.337,
        )
        """

    def testRaasQuoteTransactionResponse(self):
        """Test RaasQuoteTransactionResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
