# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from raassdkpy.models.pick_add_card_partner_params_exclude_keyof_add_card_partner_params_operation_id import PickAddCardPartnerParamsExcludeKeyofAddCardPartnerParamsOperationId  # noqa: E501

class TestPickAddCardPartnerParamsExcludeKeyofAddCardPartnerParamsOperationId(unittest.TestCase):
    """PickAddCardPartnerParamsExcludeKeyofAddCardPartnerParamsOperationId unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PickAddCardPartnerParamsExcludeKeyofAddCardPartnerParamsOperationId:
        """Test PickAddCardPartnerParamsExcludeKeyofAddCardPartnerParamsOperationId
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PickAddCardPartnerParamsExcludeKeyofAddCardPartnerParamsOperationId`
        """
        model = PickAddCardPartnerParamsExcludeKeyofAddCardPartnerParamsOperationId()  # noqa: E501
        if include_optional:
            return PickAddCardPartnerParamsExcludeKeyofAddCardPartnerParamsOperationId(
                number = '0',
                name = '',
                cardtype = 'DebitCard',
                is_primary = True,
                name_on_card = '',
                expiration_date = '0',
                security_code = '0',
                currency = '',
                country = '0',
                card_network = 'NotApplicable'
            )
        else:
            return PickAddCardPartnerParamsExcludeKeyofAddCardPartnerParamsOperationId(
                number = '0',
                name = '',
                cardtype = 'DebitCard',
                is_primary = True,
                name_on_card = '',
                expiration_date = '0',
                country = '0',
                card_network = 'NotApplicable',
        )
        """

    def testPickAddCardPartnerParamsExcludeKeyofAddCardPartnerParamsOperationId(self):
        """Test PickAddCardPartnerParamsExcludeKeyofAddCardPartnerParamsOperationId"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
