# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from raassdkpy.models.source_of_funding import SourceOfFunding  # noqa: E501

class TestSourceOfFunding(unittest.TestCase):
    """SourceOfFunding unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SourceOfFunding:
        """Test SourceOfFunding
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SourceOfFunding`
        """
        model = SourceOfFunding()  # noqa: E501
        if include_optional:
            return SourceOfFunding(
                id = '',
                is_primary = True,
                account_number = '',
                bank_entity_number = '',
                type = '',
                expiration_date = '',
                expiration_month = '',
                expiration_year = '',
                card_type = '',
                number = '',
                name = '',
                token_data = '',
                card_network = '',
                currency = ''
            )
        else:
            return SourceOfFunding(
                account_number = '',
                bank_entity_number = '',
                type = '',
                expiration_date = '',
                expiration_month = '',
                expiration_year = '',
                card_type = '',
                number = '',
                token_data = '',
        )
        """

    def testSourceOfFunding(self):
        """Test SourceOfFunding"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
