# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from raassdkpyv2.models.raas_pre_quote_values import RaasPreQuoteValues  # noqa: E501

class TestRaasPreQuoteValues(unittest.TestCase):
    """RaasPreQuoteValues unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RaasPreQuoteValues:
        """Test RaasPreQuoteValues
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RaasPreQuoteValues`
        """
        model = RaasPreQuoteValues()  # noqa: E501
        if include_optional:
            return RaasPreQuoteValues(
                exchange_rate = 1.337,
                source_fee = 1.337,
                transaction_fee = 1.337,
                destination_fee = 1.337,
                tenant_fee = 1.337,
                type = 'MobileWallet'
            )
        else:
            return RaasPreQuoteValues(
                exchange_rate = 1.337,
                source_fee = 1.337,
                transaction_fee = 1.337,
                destination_fee = 1.337,
                tenant_fee = 1.337,
                type = 'MobileWallet',
        )
        """

    def testRaasPreQuoteValues(self):
        """Test RaasPreQuoteValues"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
