# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from raassdkpyv2.models.raas_pre_quote_response import RaasPreQuoteResponse  # noqa: E501

class TestRaasPreQuoteResponse(unittest.TestCase):
    """RaasPreQuoteResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RaasPreQuoteResponse:
        """Test RaasPreQuoteResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RaasPreQuoteResponse`
        """
        model = RaasPreQuoteResponse()  # noqa: E501
        if include_optional:
            return RaasPreQuoteResponse(
                quotes = [
                    raassdkpyv2.models.raas_pre_quote_values.RaasPreQuoteValues(
                        exchange_rate = 1.337, 
                        source_fee = 1.337, 
                        transaction_fee = 1.337, 
                        destination_fee = 1.337, 
                        tenant_fee = 1.337, 
                        type = 'MobileWallet', )
                    ]
            )
        else:
            return RaasPreQuoteResponse(
                quotes = [
                    raassdkpyv2.models.raas_pre_quote_values.RaasPreQuoteValues(
                        exchange_rate = 1.337, 
                        source_fee = 1.337, 
                        transaction_fee = 1.337, 
                        destination_fee = 1.337, 
                        tenant_fee = 1.337, 
                        type = 'MobileWallet', )
                    ],
        )
        """

    def testRaasPreQuoteResponse(self):
        """Test RaasPreQuoteResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
