# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from raassdkpyv2.models.alternate_flow import AlternateFlow  # noqa: E501

class TestAlternateFlow(unittest.TestCase):
    """AlternateFlow unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAlternateFlow(self):
        """Test AlternateFlow"""
        # inst = AlternateFlow()

if __name__ == '__main__':
    unittest.main()
