# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from raassdkpyv2.models.add_bank_account_params_base import AddBankAccountParamsBase  # noqa: E501

class TestAddBankAccountParamsBase(unittest.TestCase):
    """AddBankAccountParamsBase unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AddBankAccountParamsBase:
        """Test AddBankAccountParamsBase
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AddBankAccountParamsBase`
        """
        model = AddBankAccountParamsBase()  # noqa: E501
        if include_optional:
            return AddBankAccountParamsBase(
                name = '',
                account_number = '',
                bank_account_type = 'CheckingAccount',
                bank_entity_number = '',
                is_primary = True,
                country = '',
                currency = ''
            )
        else:
            return AddBankAccountParamsBase(
                name = '',
                account_number = '',
                bank_account_type = 'CheckingAccount',
                bank_entity_number = '',
                is_primary = True,
                country = '',
        )
        """

    def testAddBankAccountParamsBase(self):
        """Test AddBankAccountParamsBase"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
