# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from raassdkpy.models.perform_resubmit_upgrade_level_params import PerformResubmitUpgradeLevelParams  # noqa: E501

class TestPerformResubmitUpgradeLevelParams(unittest.TestCase):
    """PerformResubmitUpgradeLevelParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PerformResubmitUpgradeLevelParams:
        """Test PerformResubmitUpgradeLevelParams
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PerformResubmitUpgradeLevelParams`
        """
        model = PerformResubmitUpgradeLevelParams()  # noqa: E501
        if include_optional:
            return PerformResubmitUpgradeLevelParams(
                level = 1.337,
                level_status_detail = '',
                call_location_longitude = 1.337,
                call_location_latitude = 1.337,
                address1 = '',
                address2 = '',
                address3 = '',
                address4 = '',
                state = '',
                city = '',
                zip_code = '',
                place_detail = '',
                email = '',
                country_code = '',
                date_of_birth = '',
                nationality = '',
                birth_state = '',
                gender = '',
                documents = [
                    raassdkpy.models.user_document.UserDocument(
                        id = '', 
                        type = raassdkpy.models.type.type(), 
                        sub_type = 1.337, 
                        number = '', 
                        expiration_date = '', 
                        issued_country = '', 
                        issued_date = '', 
                        user_identity_data = {
                            'key' : null
                            }, 
                        date_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                first_name = '',
                last_name = '',
                last_name2 = '',
                is_id_address_different = True
            )
        else:
            return PerformResubmitUpgradeLevelParams(
                level = 1.337,
                level_status_detail = '',
                call_location_longitude = 1.337,
                call_location_latitude = 1.337,
        )
        """

    def testPerformResubmitUpgradeLevelParams(self):
        """Test PerformResubmitUpgradeLevelParams"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
