# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from raassdkpy.models.available_payment_methods import AvailablePaymentMethods  # noqa: E501

class TestAvailablePaymentMethods(unittest.TestCase):
    """AvailablePaymentMethods unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAvailablePaymentMethods(self):
        """Test AvailablePaymentMethods"""
        # inst = AvailablePaymentMethods()

if __name__ == '__main__':
    unittest.main()
