# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from raassdkpyv2.models.attachment_responses import AttachmentResponses  # noqa: E501

class TestAttachmentResponses(unittest.TestCase):
    """AttachmentResponses unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AttachmentResponses:
        """Test AttachmentResponses
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AttachmentResponses`
        """
        model = AttachmentResponses()  # noqa: E501
        if include_optional:
            return AttachmentResponses(
                user_document = None,
                selfies = None,
                photo_id_file_name = None
            )
        else:
            return AttachmentResponses(
        )
        """

    def testAttachmentResponses(self):
        """Test AttachmentResponses"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
