# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from raassdkpyv2.models.level_one_params_requst import LevelOneParamsRequst  # noqa: E501

class TestLevelOneParamsRequst(unittest.TestCase):
    """LevelOneParamsRequst unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LevelOneParamsRequst:
        """Test LevelOneParamsRequst
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LevelOneParamsRequst`
        """
        model = LevelOneParamsRequst()  # noqa: E501
        if include_optional:
            return LevelOneParamsRequst(
                zip_code = '',
                place_detail = '',
                city = '',
                address4 = '',
                address3 = '',
                address2 = '',
                address1 = '',
                call_location_longitude = 1.337,
                call_location_latitude = 1.337,
                country_code = '',
                state = '',
                date_of_birth = '',
                gender = '',
                birth_state = '',
                user_id = ''
            )
        else:
            return LevelOneParamsRequst(
                zip_code = '',
                city = '',
                address1 = '',
                call_location_longitude = 1.337,
                call_location_latitude = 1.337,
                country_code = '',
                state = '',
                user_id = '',
        )
        """

    def testLevelOneParamsRequst(self):
        """Test LevelOneParamsRequst"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
