# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from raassdkpyv2.models.cash_operators_params_base import CashOperatorsParamsBase  # noqa: E501

class TestCashOperatorsParamsBase(unittest.TestCase):
    """CashOperatorsParamsBase unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CashOperatorsParamsBase:
        """Test CashOperatorsParamsBase
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CashOperatorsParamsBase`
        """
        model = CashOperatorsParamsBase()  # noqa: E501
        if include_optional:
            return CashOperatorsParamsBase(
                operation_ammount = 1.337
            )
        else:
            return CashOperatorsParamsBase(
        )
        """

    def testCashOperatorsParamsBase(self):
        """Test CashOperatorsParamsBase"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
