# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from raassdkpyv2.models.operation_detail import OperationDetail  # noqa: E501

class TestOperationDetail(unittest.TestCase):
    """OperationDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OperationDetail:
        """Test OperationDetail
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OperationDetail`
        """
        model = OperationDetail()  # noqa: E501
        if include_optional:
            return OperationDetail(
                id = '',
                type = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                status = '',
                reason = '',
                code = '',
                amount = 1.337,
                sender_amount = 1.337,
                recipient_amout = 1.337,
                currency = '',
                sender_currency = '',
                recipient_currency = '',
                exchange_rate = 1.337,
                from_user = raassdkpyv2.models.operation_user_detail.OperationUserDetail(
                    profile_picture_url = '', 
                    country = '', 
                    image_url = '', 
                    email = '', 
                    phone_number = '', 
                    last_name = '', 
                    first_name = '', ),
                to_user = raassdkpyv2.models.operation_user_detail.OperationUserDetail(
                    profile_picture_url = '', 
                    country = '', 
                    image_url = '', 
                    email = '', 
                    phone_number = '', 
                    last_name = '', 
                    first_name = '', ),
                attribution_link = '',
                is_ignored = True,
                ignored_data = None
            )
        else:
            return OperationDetail(
                id = '',
                type = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                status = '',
                code = '',
                amount = 1.337,
                sender_amount = 1.337,
                recipient_amout = 1.337,
                from_user = raassdkpyv2.models.operation_user_detail.OperationUserDetail(
                    profile_picture_url = '', 
                    country = '', 
                    image_url = '', 
                    email = '', 
                    phone_number = '', 
                    last_name = '', 
                    first_name = '', ),
                to_user = raassdkpyv2.models.operation_user_detail.OperationUserDetail(
                    profile_picture_url = '', 
                    country = '', 
                    image_url = '', 
                    email = '', 
                    phone_number = '', 
                    last_name = '', 
                    first_name = '', ),
        )
        """

    def testOperationDetail(self):
        """Test OperationDetail"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
