# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from raassdkpy.models.send_money_partner_params import SendMoneyPartnerParams  # noqa: E501

class TestSendMoneyPartnerParams(unittest.TestCase):
    """SendMoneyPartnerParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SendMoneyPartnerParams:
        """Test SendMoneyPartnerParams
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SendMoneyPartnerParams`
        """
        model = SendMoneyPartnerParams()  # noqa: E501
        if include_optional:
            return SendMoneyPartnerParams(
                quotation_id = '',
                currency = '',
                amount = 1.337,
                reason = '',
                destination_payment_method_id = '',
                source_payment_method_id = '',
                correlation_id = '',
                send_to = ''
            )
        else:
            return SendMoneyPartnerParams(
                quotation_id = '',
                correlation_id = '',
        )
        """

    def testSendMoneyPartnerParams(self):
        """Test SendMoneyPartnerParams"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
