# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from raassdkpy.models.corridor_dto import CorridorDTO  # noqa: E501

class TestCorridorDTO(unittest.TestCase):
    """CorridorDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CorridorDTO:
        """Test CorridorDTO
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CorridorDTO`
        """
        model = CorridorDTO()  # noqa: E501
        if include_optional:
            return CorridorDTO(
                id = '',
                source_payment_method_type = 'MobileWallet',
                destination_payment_method_type = 'MobileWallet',
                lower_limit = 1.337,
                upper_limit = 1.337,
                fees = None,
                corridor_requirements = None,
                is_active = True,
                source_country = '',
                destination_country = ''
            )
        else:
            return CorridorDTO(
                id = '',
                source_payment_method_type = 'MobileWallet',
                destination_payment_method_type = 'MobileWallet',
                lower_limit = 1.337,
                upper_limit = 1.337,
                fees = None,
                corridor_requirements = None,
                is_active = True,
                source_country = '',
                destination_country = '',
        )
        """

    def testCorridorDTO(self):
        """Test CorridorDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
