# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from raassdkpy.models.is_phone_available_request import IsPhoneAvailableRequest  # noqa: E501

class TestIsPhoneAvailableRequest(unittest.TestCase):
    """IsPhoneAvailableRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IsPhoneAvailableRequest:
        """Test IsPhoneAvailableRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IsPhoneAvailableRequest`
        """
        model = IsPhoneAvailableRequest()  # noqa: E501
        if include_optional:
            return IsPhoneAvailableRequest(
                phone = ''
            )
        else:
            return IsPhoneAvailableRequest(
                phone = '',
        )
        """

    def testIsPhoneAvailableRequest(self):
        """Test IsPhoneAvailableRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
