# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import Any, Optional
from pydantic import BaseModel, Field, StrictStr

class BaseIdentity(BaseModel):
    """
    BaseIdentity
    """
    surname: Optional[StrictStr] = None
    names: Optional[StrictStr] = None
    dob: Optional[datetime] = None
    dob_raw: Optional[StrictStr] = Field(None, alias="dobRaw")
    address: Optional[StrictStr] = None
    country: Optional[StrictStr] = None
    id_country: Optional[StrictStr] = Field(None, alias="idCountry")
    state: Optional[StrictStr] = None
    city: Optional[StrictStr] = None
    county: Optional[StrictStr] = None
    district: Optional[StrictStr] = None
    id: Optional[StrictStr] = None
    exp_date: Optional[datetime] = Field(None, alias="expDate")
    exp_date_raw: Optional[StrictStr] = Field(None, alias="expDateRaw")
    gender: Optional[StrictStr] = None
    doc_type: Optional[StrictStr] = Field(None, alias="docType")
    nationality: Optional[StrictStr] = None
    id_validated: Optional[StrictStr] = Field(None, alias="idValidated")
    id_name: Optional[StrictStr] = Field(None, alias="idName")
    zipcode: Optional[StrictStr] = None
    state_code: Optional[StrictStr] = None
    county_code: Optional[StrictStr] = None
    section_code: Optional[StrictStr] = None
    locality_code: Optional[StrictStr] = None
    first_name: Optional[StrictStr] = Field(None, alias="firstName")
    last_name: Optional[StrictStr] = Field(None, alias="lastName")
    second_lastname: Optional[StrictStr] = Field(None, alias="secondLastname")
    second_name: Optional[Any] = Field(None, alias="secondName")
    marital_status: Optional[StrictStr] = Field(None, alias="maritalStatus")
    maiden_name: Optional[StrictStr] = Field(None, alias="maidenName")
    third_name: Optional[StrictStr] = Field(None, alias="thirdName")
    subtype: Optional[StrictStr] = None
    __properties = ["surname", "names", "dob", "dobRaw", "address", "country", "idCountry", "state", "city", "county", "district", "id", "expDate", "expDateRaw", "gender", "docType", "nationality", "idValidated", "idName", "zipcode", "state_code", "county_code", "section_code", "locality_code", "firstName", "lastName", "secondLastname", "secondName", "maritalStatus", "maidenName", "thirdName", "subtype"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> BaseIdentity:
        """Create an instance of BaseIdentity from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if second_name (nullable) is None
        # and __fields_set__ contains the field
        if self.second_name is None and "second_name" in self.__fields_set__:
            _dict['secondName'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> BaseIdentity:
        """Create an instance of BaseIdentity from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return BaseIdentity.parse_obj(obj)

        _obj = BaseIdentity.parse_obj({
            "surname": obj.get("surname"),
            "names": obj.get("names"),
            "dob": obj.get("dob"),
            "dob_raw": obj.get("dobRaw"),
            "address": obj.get("address"),
            "country": obj.get("country"),
            "id_country": obj.get("idCountry"),
            "state": obj.get("state"),
            "city": obj.get("city"),
            "county": obj.get("county"),
            "district": obj.get("district"),
            "id": obj.get("id"),
            "exp_date": obj.get("expDate"),
            "exp_date_raw": obj.get("expDateRaw"),
            "gender": obj.get("gender"),
            "doc_type": obj.get("docType"),
            "nationality": obj.get("nationality"),
            "id_validated": obj.get("idValidated"),
            "id_name": obj.get("idName"),
            "zipcode": obj.get("zipcode"),
            "state_code": obj.get("state_code"),
            "county_code": obj.get("county_code"),
            "section_code": obj.get("section_code"),
            "locality_code": obj.get("locality_code"),
            "first_name": obj.get("firstName"),
            "last_name": obj.get("lastName"),
            "second_lastname": obj.get("secondLastname"),
            "second_name": obj.get("secondName"),
            "marital_status": obj.get("maritalStatus"),
            "maiden_name": obj.get("maidenName"),
            "third_name": obj.get("thirdName"),
            "subtype": obj.get("subtype")
        })
        return _obj


