# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class AvailablePaymentMethods(str, Enum):
    """
    AvailablePaymentMethods
    """

    """
    allowed enum values
    """
    MOBILEWALLET = 'MobileWallet'
    BANKACCOUNT = 'BankAccount'
    DEBITCARD = 'DebitCard'
    CREDITCARD = 'CreditCard'
    CASHLOADLOCATION = 'CashLoadLocation'
    APPLEDIGITALWALLET = 'AppleDigitalWallet'
    GOOGLEDIGITALWALLET = 'GoogleDigitalWallet'

    @classmethod
    def from_json(cls, json_str: str) -> AvailablePaymentMethods:
        """Create an instance of AvailablePaymentMethods from a JSON string"""
        return AvailablePaymentMethods(json.loads(json_str))


