# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictStr
from pydantic import Field
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class CIPData(BaseModel):
    """
    CIPData
    """ # noqa: E501
    address: Optional[StrictStr] = None
    city: Optional[StrictStr] = None
    country: Optional[StrictStr] = None
    county: Optional[StrictStr] = None
    district: Optional[StrictStr] = None
    dob: Optional[datetime] = None
    dob_raw: Optional[StrictStr] = Field(default=None, alias="dobRaw")
    doc_type: Optional[StrictStr] = Field(default=None, alias="docType")
    exp_date: Optional[datetime] = Field(default=None, alias="expDate")
    exp_date_raw: Optional[StrictStr] = Field(default=None, alias="expDateRaw")
    first_name: Optional[StrictStr] = Field(default=None, alias="firstName")
    gender: Optional[StrictStr] = None
    id: Optional[StrictStr] = None
    id_country: Optional[StrictStr] = Field(default=None, alias="idCountry")
    id_name: Optional[StrictStr] = Field(default=None, alias="idName")
    last_name: Optional[StrictStr] = Field(default=None, alias="lastName")
    names: Optional[StrictStr] = None
    nationality: Optional[StrictStr] = None
    second_lastname: Optional[StrictStr] = Field(default=None, alias="secondLastname")
    second_name: Optional[StrictStr] = Field(default=None, alias="secondName")
    state: Optional[StrictStr] = None
    subtype: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["address", "city", "country", "county", "district", "dob", "dobRaw", "docType", "expDate", "expDateRaw", "firstName", "gender", "id", "idCountry", "idName", "lastName", "names", "nationality", "secondLastname", "secondName", "state", "subtype"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CIPData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of CIPData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "address": obj.get("address"),
            "city": obj.get("city"),
            "country": obj.get("country"),
            "county": obj.get("county"),
            "district": obj.get("district"),
            "dob": obj.get("dob"),
            "dobRaw": obj.get("dobRaw"),
            "docType": obj.get("docType"),
            "expDate": obj.get("expDate"),
            "expDateRaw": obj.get("expDateRaw"),
            "firstName": obj.get("firstName"),
            "gender": obj.get("gender"),
            "id": obj.get("id"),
            "idCountry": obj.get("idCountry"),
            "idName": obj.get("idName"),
            "lastName": obj.get("lastName"),
            "names": obj.get("names"),
            "nationality": obj.get("nationality"),
            "secondLastname": obj.get("secondLastname"),
            "secondName": obj.get("secondName"),
            "state": obj.get("state"),
            "subtype": obj.get("subtype")
        })
        return _obj


