# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class Language(str, Enum):
    """
    Language
    """

    """
    allowed enum values
    """
    EN = 'en'
    ES = 'es'

    @classmethod
    def from_json(cls, json_str: str) -> Language:
        """Create an instance of Language from a JSON string"""
        return Language(json.loads(json_str))


