# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List
from pydantic import BaseModel, StrictStr
from pydantic import Field
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class OperationContactData(BaseModel):
    """
    OperationContactData
    """ # noqa: E501
    id: StrictStr
    contact_id: StrictStr = Field(alias="contactId")
    country_code: StrictStr = Field(alias="countryCode")
    mobile_phone: StrictStr = Field(alias="mobilePhone")
    first_name: StrictStr = Field(alias="firstName")
    middle_name: StrictStr = Field(alias="middleName")
    last_name: StrictStr = Field(alias="lastName")
    last_name2: StrictStr = Field(alias="lastName2")
    email: StrictStr
    relationship: StrictStr
    __properties: ClassVar[List[str]] = ["id", "contactId", "countryCode", "mobilePhone", "firstName", "middleName", "lastName", "lastName2", "email", "relationship"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of OperationContactData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of OperationContactData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "contactId": obj.get("contactId"),
            "countryCode": obj.get("countryCode"),
            "mobilePhone": obj.get("mobilePhone"),
            "firstName": obj.get("firstName"),
            "middleName": obj.get("middleName"),
            "lastName": obj.get("lastName"),
            "lastName2": obj.get("lastName2"),
            "email": obj.get("email"),
            "relationship": obj.get("relationship")
        })
        return _obj


