# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import Optional, Union
from pydantic import BaseModel, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from raassdkpyv2.models.ignored_operation_data import IgnoredOperationData
from raassdkpyv2.models.operation_user_detail import OperationUserDetail
from raassdkpyv2.models.payment_method_response import PaymentMethodResponse

class OperationDetailResponse(BaseModel):
    """
    OperationDetailResponse
    """
    tenantfee: Optional[Union[StrictFloat, StrictInt]] = None
    ignored_data: Optional[IgnoredOperationData] = Field(None, alias="ignoredData")
    is_ignored: Optional[StrictBool] = Field(None, alias="isIgnored")
    attribution_link: Optional[StrictStr] = Field(None, alias="attributionLink")
    to_user: OperationUserDetail = Field(..., alias="toUser")
    from_user: OperationUserDetail = Field(..., alias="fromUser")
    has_reference_code: Optional[StrictBool] = Field(None, alias="hasReferenceCode")
    exchange_rate: Optional[Union[StrictFloat, StrictInt]] = Field(None, alias="exchangeRate")
    destination_fee: Optional[Union[StrictFloat, StrictInt]] = Field(None, alias="destinationFee")
    transaction_fee: Optional[Union[StrictFloat, StrictInt]] = Field(None, alias="transactionFee")
    source_fee: Optional[Union[StrictFloat, StrictInt]] = Field(None, alias="sourceFee")
    destination_payment_method: Optional[PaymentMethodResponse] = Field(None, alias="destinationPaymentMethod")
    source_payment_method: Optional[PaymentMethodResponse] = Field(None, alias="sourcePaymentMethod")
    recipient_currency: Optional[StrictStr] = Field(None, alias="recipientCurrency")
    sender_currency: Optional[StrictStr] = Field(None, alias="senderCurrency")
    currency: Optional[StrictStr] = None
    show_warning_screen: StrictBool = Field(..., alias="showWarningScreen")
    sender_amount: Optional[Union[StrictFloat, StrictInt]] = Field(None, alias="senderAmount")
    recipient_amout: Union[StrictFloat, StrictInt] = Field(..., alias="recipientAmout")
    code: StrictStr = Field(...)
    reason: Optional[StrictStr] = None
    mobile_status: Optional[StrictStr] = Field(None, alias="mobileStatus")
    status_details: Optional[StrictStr] = Field(None, alias="statusDetails")
    status: StrictStr = Field(...)
    amount: Union[StrictFloat, StrictInt] = Field(...)
    created_at: datetime = Field(..., alias="createdAt")
    type: StrictStr = Field(...)
    correlation_id: StrictStr = Field(..., alias="correlationId")
    plat_id: Optional[StrictStr] = Field(None, alias="platId")
    id: StrictStr = Field(...)
    __properties = ["tenantfee", "ignoredData", "isIgnored", "attributionLink", "toUser", "fromUser", "hasReferenceCode", "exchangeRate", "destinationFee", "transactionFee", "sourceFee", "destinationPaymentMethod", "sourcePaymentMethod", "recipientCurrency", "senderCurrency", "currency", "showWarningScreen", "senderAmount", "recipientAmout", "code", "reason", "mobileStatus", "statusDetails", "status", "amount", "createdAt", "type", "correlationId", "platId", "id"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> OperationDetailResponse:
        """Create an instance of OperationDetailResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of ignored_data
        if self.ignored_data:
            _dict['ignoredData'] = self.ignored_data.to_dict()
        # override the default output from pydantic by calling `to_dict()` of to_user
        if self.to_user:
            _dict['toUser'] = self.to_user.to_dict()
        # override the default output from pydantic by calling `to_dict()` of from_user
        if self.from_user:
            _dict['fromUser'] = self.from_user.to_dict()
        # override the default output from pydantic by calling `to_dict()` of destination_payment_method
        if self.destination_payment_method:
            _dict['destinationPaymentMethod'] = self.destination_payment_method.to_dict()
        # override the default output from pydantic by calling `to_dict()` of source_payment_method
        if self.source_payment_method:
            _dict['sourcePaymentMethod'] = self.source_payment_method.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> OperationDetailResponse:
        """Create an instance of OperationDetailResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return OperationDetailResponse.parse_obj(obj)

        _obj = OperationDetailResponse.parse_obj({
            "tenantfee": obj.get("tenantfee"),
            "ignored_data": IgnoredOperationData.from_dict(obj.get("ignoredData")) if obj.get("ignoredData") is not None else None,
            "is_ignored": obj.get("isIgnored"),
            "attribution_link": obj.get("attributionLink"),
            "to_user": OperationUserDetail.from_dict(obj.get("toUser")) if obj.get("toUser") is not None else None,
            "from_user": OperationUserDetail.from_dict(obj.get("fromUser")) if obj.get("fromUser") is not None else None,
            "has_reference_code": obj.get("hasReferenceCode"),
            "exchange_rate": obj.get("exchangeRate"),
            "destination_fee": obj.get("destinationFee"),
            "transaction_fee": obj.get("transactionFee"),
            "source_fee": obj.get("sourceFee"),
            "destination_payment_method": PaymentMethodResponse.from_dict(obj.get("destinationPaymentMethod")) if obj.get("destinationPaymentMethod") is not None else None,
            "source_payment_method": PaymentMethodResponse.from_dict(obj.get("sourcePaymentMethod")) if obj.get("sourcePaymentMethod") is not None else None,
            "recipient_currency": obj.get("recipientCurrency"),
            "sender_currency": obj.get("senderCurrency"),
            "currency": obj.get("currency"),
            "show_warning_screen": obj.get("showWarningScreen"),
            "sender_amount": obj.get("senderAmount"),
            "recipient_amout": obj.get("recipientAmout"),
            "code": obj.get("code"),
            "reason": obj.get("reason"),
            "mobile_status": obj.get("mobileStatus"),
            "status_details": obj.get("statusDetails"),
            "status": obj.get("status"),
            "amount": obj.get("amount"),
            "created_at": obj.get("createdAt"),
            "type": obj.get("type"),
            "correlation_id": obj.get("correlationId"),
            "plat_id": obj.get("platId"),
            "id": obj.get("id")
        })
        return _obj


