# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional, Union
from pydantic import BaseModel, StrictBool, StrictFloat, StrictInt, StrictStr
from pydantic import Field
from raassdkpyv2.models.user_document import UserDocument
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class PerformResubmitUpgradeLevelParams(BaseModel):
    """
    PerformResubmitUpgradeLevelParams
    """ # noqa: E501
    level: Union[StrictFloat, StrictInt]
    level_status_detail: StrictStr = Field(alias="levelStatusDetail")
    call_location_longitude: Union[StrictFloat, StrictInt] = Field(alias="callLocationLongitude")
    call_location_latitude: Union[StrictFloat, StrictInt] = Field(alias="callLocationLatitude")
    address1: Optional[StrictStr] = None
    address2: Optional[StrictStr] = None
    address3: Optional[StrictStr] = None
    address4: Optional[StrictStr] = None
    state: Optional[StrictStr] = None
    city: Optional[StrictStr] = None
    zip_code: Optional[StrictStr] = Field(default=None, alias="zipCode")
    place_detail: Optional[StrictStr] = Field(default=None, alias="placeDetail")
    email: Optional[StrictStr] = None
    country_code: Optional[StrictStr] = Field(default=None, alias="countryCode")
    date_of_birth: Optional[StrictStr] = Field(default=None, alias="dateOfBirth")
    nationality: Optional[StrictStr] = None
    birth_state: Optional[StrictStr] = Field(default=None, alias="birthState")
    gender: Optional[StrictStr] = None
    documents: Optional[List[UserDocument]] = None
    first_name: Optional[StrictStr] = Field(default=None, alias="firstName")
    last_name: Optional[StrictStr] = Field(default=None, alias="lastName")
    last_name2: Optional[StrictStr] = Field(default=None, alias="lastName2")
    is_id_address_different: Optional[StrictBool] = Field(default=None, alias="isIdAddressDifferent")
    __properties: ClassVar[List[str]] = ["level", "levelStatusDetail", "callLocationLongitude", "callLocationLatitude", "address1", "address2", "address3", "address4", "state", "city", "zipCode", "placeDetail", "email", "countryCode", "dateOfBirth", "nationality", "birthState", "gender", "documents", "firstName", "lastName", "lastName2", "isIdAddressDifferent"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PerformResubmitUpgradeLevelParams from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in documents (list)
        _items = []
        if self.documents:
            for _item in self.documents:
                if _item:
                    _items.append(_item.to_dict())
            _dict['documents'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of PerformResubmitUpgradeLevelParams from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "level": obj.get("level"),
            "levelStatusDetail": obj.get("levelStatusDetail"),
            "callLocationLongitude": obj.get("callLocationLongitude"),
            "callLocationLatitude": obj.get("callLocationLatitude"),
            "address1": obj.get("address1"),
            "address2": obj.get("address2"),
            "address3": obj.get("address3"),
            "address4": obj.get("address4"),
            "state": obj.get("state"),
            "city": obj.get("city"),
            "zipCode": obj.get("zipCode"),
            "placeDetail": obj.get("placeDetail"),
            "email": obj.get("email"),
            "countryCode": obj.get("countryCode"),
            "dateOfBirth": obj.get("dateOfBirth"),
            "nationality": obj.get("nationality"),
            "birthState": obj.get("birthState"),
            "gender": obj.get("gender"),
            "documents": [UserDocument.from_dict(_item) for _item in obj.get("documents")] if obj.get("documents") is not None else None,
            "firstName": obj.get("firstName"),
            "lastName": obj.get("lastName"),
            "lastName2": obj.get("lastName2"),
            "isIdAddressDifferent": obj.get("isIdAddressDifferent")
        })
        return _obj


