# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field, StrictBool, StrictStr

class PlaidBankValidationResponse(BaseModel):
    """
    PlaidBankValidationResponse
    """
    success: StrictBool = Field(...)
    access_token: StrictStr = Field(..., alias="accessToken")
    item_id: StrictStr = Field(..., alias="itemId")
    account_type: StrictStr = Field(..., alias="accountType")
    account_sub_type: StrictStr = Field(..., alias="accountSubType")
    account_name: StrictStr = Field(..., alias="accountName")
    account_number: StrictStr = Field(..., alias="accountNumber")
    account_routing: StrictStr = Field(..., alias="accountRouting")
    bank_name: StrictStr = Field(..., alias="bankName")
    __properties = ["success", "accessToken", "itemId", "accountType", "accountSubType", "accountName", "accountNumber", "accountRouting", "bankName"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> PlaidBankValidationResponse:
        """Create an instance of PlaidBankValidationResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> PlaidBankValidationResponse:
        """Create an instance of PlaidBankValidationResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return PlaidBankValidationResponse.parse_obj(obj)

        _obj = PlaidBankValidationResponse.parse_obj({
            "success": obj.get("success"),
            "access_token": obj.get("accessToken"),
            "item_id": obj.get("itemId"),
            "account_type": obj.get("accountType"),
            "account_sub_type": obj.get("accountSubType"),
            "account_name": obj.get("accountName"),
            "account_number": obj.get("accountNumber"),
            "account_routing": obj.get("accountRouting"),
            "bank_name": obj.get("bankName")
        })
        return _obj


