# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional, Union
from pydantic import BaseModel, StrictBool, StrictFloat, StrictInt, StrictStr
from pydantic import Field
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class QuickAmount(BaseModel):
    """
    QuickAmount
    """ # noqa: E501
    amount: Union[StrictFloat, StrictInt]
    is_most_frequent: Optional[StrictBool] = Field(default=None, description="This config is to display the most frequent quick amount in the UI", alias="isMostFrequent")
    exchange: Union[StrictFloat, StrictInt]
    currency_code_src: StrictStr = Field(alias="currencyCodeSrc")
    currency_code_dest: StrictStr = Field(alias="currencyCodeDest")
    __properties: ClassVar[List[str]] = ["amount", "isMostFrequent", "exchange", "currencyCodeSrc", "currencyCodeDest"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of QuickAmount from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of QuickAmount from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "amount": obj.get("amount"),
            "isMostFrequent": obj.get("isMostFrequent"),
            "exchange": obj.get("exchange"),
            "currencyCodeSrc": obj.get("currencyCodeSrc"),
            "currencyCodeDest": obj.get("currencyCodeDest")
        })
        return _obj


