# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictBool, StrictStr, field_validator
from pydantic import Field
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class RaaSPartnerPaymentMethod(BaseModel):
    """
    RaaSPartnerPaymentMethod
    """ # noqa: E501
    currency: Optional[StrictStr] = None
    bank_account_type: Optional[StrictStr] = Field(default=None, alias="bankAccountType")
    cardtype: Optional[StrictStr] = None
    number: Optional[StrictStr] = None
    account_number: Optional[StrictStr] = Field(default=None, alias="accountNumber")
    bank_entity_number: Optional[StrictStr] = Field(default=None, alias="bankEntityNumber")
    bank_name: Optional[StrictStr] = Field(default=None, alias="bankName")
    is_primary: Optional[StrictBool] = Field(default=None, alias="isPrimary")
    name: Optional[StrictStr] = None
    id: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["currency", "bankAccountType", "cardtype", "number", "accountNumber", "bankEntityNumber", "bankName", "isPrimary", "name", "id"]

    @field_validator('bank_account_type')
    def bank_account_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('CheckingAccount', 'SavingsAccount', 'OtherAccount'):
            raise ValueError("must be one of enum values ('CheckingAccount', 'SavingsAccount', 'OtherAccount')")
        return value

    @field_validator('cardtype')
    def cardtype_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('DebitCard', 'CreditCard'):
            raise ValueError("must be one of enum values ('DebitCard', 'CreditCard')")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of RaaSPartnerPaymentMethod from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of RaaSPartnerPaymentMethod from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "currency": obj.get("currency"),
            "bankAccountType": obj.get("bankAccountType"),
            "cardtype": obj.get("cardtype"),
            "number": obj.get("number"),
            "accountNumber": obj.get("accountNumber"),
            "bankEntityNumber": obj.get("bankEntityNumber"),
            "bankName": obj.get("bankName"),
            "isPrimary": obj.get("isPrimary"),
            "name": obj.get("name"),
            "id": obj.get("id")
        })
        return _obj


