# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Union
from pydantic import BaseModel, Field, StrictFloat, StrictInt
from raassdkpyv2.models.available_payment_methods import AvailablePaymentMethods

class RaasPreQuoteValues(BaseModel):
    """
    RaasPreQuoteValues
    """
    exchange_rate: Union[StrictFloat, StrictInt] = Field(..., alias="ExchangeRate")
    source_fee: Union[StrictFloat, StrictInt] = Field(..., alias="SourceFee")
    transaction_fee: Union[StrictFloat, StrictInt] = Field(..., alias="TransactionFee")
    destination_fee: Union[StrictFloat, StrictInt] = Field(..., alias="DestinationFee")
    tenant_fee: Union[StrictFloat, StrictInt] = Field(..., alias="TenantFee")
    type: AvailablePaymentMethods = Field(..., alias="Type")
    __properties = ["ExchangeRate", "SourceFee", "TransactionFee", "DestinationFee", "TenantFee", "Type"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model"""
        return pprint.pformat(self.model_dump(by_alias=False))

    def to_json(self) -> str:
        """Returns the JSON representation of the model"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> RaasPreQuoteValues:
        """Create an instance of RaasPreQuoteValues from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model"""
        _dict = self.model_dump(by_alias=False,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> RaasPreQuoteValues:
        """Create an instance of RaasPreQuoteValues from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return RaasPreQuoteValues.model_validate(obj)

        _obj = RaasPreQuoteValues.model_validate(obj)
        return _obj


