# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictBool, StrictStr
from pydantic import Field
from raassdkpyv2.models.operation_data import OperationData
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class SendMoneyResponse(BaseModel):
    """
    SendMoneyResponse
    """ # noqa: E501
    operation: Optional[OperationData] = None
    landing_port_url: Optional[StrictStr] = Field(default=None, alias="landingPortUrl")
    is_landing_port_flow: Optional[StrictBool] = Field(default=None, alias="isLandingPortFlow")
    plat_id: StrictStr = Field(alias="platId")
    id: StrictStr = Field(description="RaaS Operation Id")
    link: StrictStr = Field(description="kochava link")
    __properties: ClassVar[List[str]] = ["operation", "landingPortUrl", "isLandingPortFlow", "platId", "id", "link"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of SendMoneyResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of operation
        if self.operation:
            _dict['operation'] = self.operation.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of SendMoneyResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "operation": OperationData.from_dict(obj.get("operation")) if obj.get("operation") is not None else None,
            "landingPortUrl": obj.get("landingPortUrl"),
            "isLandingPortFlow": obj.get("isLandingPortFlow"),
            "platId": obj.get("platId"),
            "id": obj.get("id"),
            "link": obj.get("link")
        })
        return _obj


