# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional, Union
from pydantic import BaseModel, StrictFloat, StrictInt, StrictStr
from pydantic import Field
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class SendMoneyPartnerParams(BaseModel):
    """
    SendMoneyPartnerParams
    """ # noqa: E501
    quotation_id: StrictStr = Field(alias="quotationId")
    currency: Optional[StrictStr] = None
    amount: Optional[Union[StrictFloat, StrictInt]] = None
    reason: Optional[StrictStr] = None
    destination_payment_method_id: Optional[StrictStr] = Field(default=None, alias="destinationPaymentMethodId")
    source_payment_method_id: Optional[StrictStr] = Field(default=None, alias="sourcePaymentMethodId")
    correlation_id: StrictStr = Field(alias="correlationId")
    send_to: Optional[StrictStr] = Field(default=None, alias="sendTo")
    __properties: ClassVar[List[str]] = ["quotationId", "currency", "amount", "reason", "destinationPaymentMethodId", "sourcePaymentMethodId", "correlationId", "sendTo"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of SendMoneyPartnerParams from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of SendMoneyPartnerParams from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "quotationId": obj.get("quotationId"),
            "currency": obj.get("currency"),
            "amount": obj.get("amount"),
            "reason": obj.get("reason"),
            "destinationPaymentMethodId": obj.get("destinationPaymentMethodId"),
            "sourcePaymentMethodId": obj.get("sourcePaymentMethodId"),
            "correlationId": obj.get("correlationId"),
            "sendTo": obj.get("sendTo")
        })
        return _obj


