# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import Any, ClassVar, Dict, List, Optional, Union
from pydantic import BaseModel, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from pydantic import Field
from raassdkpyv2.models.cip import CIP
from raassdkpyv2.models.i_phone_info import IPhoneInfo
from raassdkpyv2.models.language import Language
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class User(BaseModel):
    """
    User
    """ # noqa: E501
    id: StrictStr
    email: Optional[StrictStr] = None
    first_name: Optional[StrictStr] = Field(default=None, alias="firstName")
    last_name: Optional[StrictStr] = Field(default=None, alias="lastName")
    middle_name: Optional[StrictStr] = Field(default=None, alias="middleName")
    second_last_name: Optional[StrictStr] = Field(default=None, alias="secondLastName")
    address1: Optional[StrictStr] = None
    address2: Optional[StrictStr] = None
    place_id: Optional[StrictStr] = Field(default=None, alias="placeId")
    country: Optional[StrictStr] = None
    address_description: Optional[StrictStr] = Field(default=None, description="Here we save some description about direcction for example: Local 304, next to the grocery store", alias="addressDescription")
    gender: Optional[StrictStr] = None
    dob: Optional[datetime] = None
    country_id: Optional[StrictStr] = None
    status: Optional[StrictStr] = None
    phone_number: Optional[StrictStr] = Field(default=None, alias="phoneNumber")
    phone_verified: Optional[StrictBool] = Field(default=None, alias="phoneVerified")
    cip: Optional[CIP] = None
    first_time: Optional[StrictBool] = Field(default=None, alias="firstTime")
    country_code: Optional[StrictStr] = Field(default=None, alias="countryCode")
    city: Optional[StrictStr] = None
    zipcode: Optional[StrictStr] = None
    state: Optional[StrictStr] = None
    birth_state: Optional[StrictStr] = Field(default=None, alias="birthState")
    place_detail: Optional[StrictStr] = Field(default=None, description="Here we save the google maps places address details", alias="placeDetail")
    pincode: Optional[StrictStr] = Field(default=None, description="Pincode - used to validate user in Raas")
    has_pincode: Optional[StrictBool] = Field(default=None, alias="hasPincode")
    password: Optional[StrictStr] = Field(default=None, description="Used to store Numi Plat pincode. It's not used to validate  user in Raas")
    phone_info: Optional[IPhoneInfo] = Field(default=None, alias="phoneInfo")
    tenant_id: StrictStr = Field(alias="tenantId")
    tenant_code: StrictStr = Field(alias="tenantCode")
    latitude: Optional[Union[StrictFloat, StrictInt]] = None
    longitude: Optional[Union[StrictFloat, StrictInt]] = None
    profile_picture_url: Optional[StrictStr] = Field(default=None, alias="profilePictureUrl")
    custom_country_code: Optional[StrictStr] = Field(default=None, alias="customCountryCode")
    facebook_public_user_name: Optional[StrictStr] = Field(default=None, alias="facebookPublicUserName")
    instagram_public_user_name: Optional[StrictStr] = Field(default=None, alias="instagramPublicUserName")
    account_code: Optional[StrictStr] = Field(default=None, alias="accountCode")
    lang: Optional[Language] = None
    has_payment_method: Optional[StrictBool] = Field(default=None, alias="hasPaymentMethod")
    show_landing: Optional[StrictBool] = Field(default=None, alias="showLanding")
    show_cash_landing: Optional[StrictBool] = Field(default=None, alias="showCashLanding")
    is_widget_user: Optional[StrictBool] = Field(default=None, alias="isWidgetUser")
    subscriber_type: Optional[StrictStr] = Field(default=None, alias="subscriberType")
    document_number: Optional[StrictStr] = Field(default=None, alias="documentNumber")
    __properties: ClassVar[List[str]] = ["id", "email", "firstName", "lastName", "middleName", "secondLastName", "address1", "address2", "placeId", "country", "addressDescription", "gender", "dob", "country_id", "status", "phoneNumber", "phoneVerified", "cip", "firstTime", "countryCode", "city", "zipcode", "state", "birthState", "placeDetail", "pincode", "hasPincode", "password", "phoneInfo", "tenantId", "tenantCode", "latitude", "longitude", "profilePictureUrl", "customCountryCode", "facebookPublicUserName", "instagramPublicUserName", "accountCode", "lang", "hasPaymentMethod", "showLanding", "showCashLanding", "isWidgetUser", "subscriberType", "documentNumber"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('new', 'ready'):
            raise ValueError("must be one of enum values ('new', 'ready')")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of User from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of cip
        if self.cip:
            _dict['cip'] = self.cip.to_dict()
        # override the default output from pydantic by calling `to_dict()` of phone_info
        if self.phone_info:
            _dict['phoneInfo'] = self.phone_info.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of User from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "email": obj.get("email"),
            "firstName": obj.get("firstName"),
            "lastName": obj.get("lastName"),
            "middleName": obj.get("middleName"),
            "secondLastName": obj.get("secondLastName"),
            "address1": obj.get("address1"),
            "address2": obj.get("address2"),
            "placeId": obj.get("placeId"),
            "country": obj.get("country"),
            "addressDescription": obj.get("addressDescription"),
            "gender": obj.get("gender"),
            "dob": obj.get("dob"),
            "country_id": obj.get("country_id"),
            "status": obj.get("status"),
            "phoneNumber": obj.get("phoneNumber"),
            "phoneVerified": obj.get("phoneVerified"),
            "cip": CIP.from_dict(obj.get("cip")) if obj.get("cip") is not None else None,
            "firstTime": obj.get("firstTime"),
            "countryCode": obj.get("countryCode"),
            "city": obj.get("city"),
            "zipcode": obj.get("zipcode"),
            "state": obj.get("state"),
            "birthState": obj.get("birthState"),
            "placeDetail": obj.get("placeDetail"),
            "pincode": obj.get("pincode"),
            "hasPincode": obj.get("hasPincode"),
            "password": obj.get("password"),
            "phoneInfo": IPhoneInfo.from_dict(obj.get("phoneInfo")) if obj.get("phoneInfo") is not None else None,
            "tenantId": obj.get("tenantId"),
            "tenantCode": obj.get("tenantCode"),
            "latitude": obj.get("latitude"),
            "longitude": obj.get("longitude"),
            "profilePictureUrl": obj.get("profilePictureUrl"),
            "customCountryCode": obj.get("customCountryCode"),
            "facebookPublicUserName": obj.get("facebookPublicUserName"),
            "instagramPublicUserName": obj.get("instagramPublicUserName"),
            "accountCode": obj.get("accountCode"),
            "lang": obj.get("lang"),
            "hasPaymentMethod": obj.get("hasPaymentMethod"),
            "showLanding": obj.get("showLanding"),
            "showCashLanding": obj.get("showCashLanding"),
            "isWidgetUser": obj.get("isWidgetUser"),
            "subscriberType": obj.get("subscriberType"),
            "documentNumber": obj.get("documentNumber")
        })
        return _obj


